<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1568" started-at="2017-09-13T16:15:55Z" finished-at="2017-09-13T16:15:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1568" started-at="2017-09-13T16:15:55Z" finished-at="2017-09-13T16:15:57Z">
      <class name="tests.Persontest">
        <test-method status="PASS" signature="getPersonById()[pri:0, instance:tests.Persontest@e45f292]" name="getPersonById" duration-ms="1432" started-at="2017-09-13T19:15:55Z" finished-at="2017-09-13T19:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPersonById -->
        <test-method status="PASS" signature="addPerson()[pri:0, instance:tests.Persontest@e45f292]" name="addPerson" duration-ms="30" started-at="2017-09-13T19:15:57Z" depends-on-methods="tests.Persontest.getPersonById" finished-at="2017-09-13T19:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPerson -->
        <test-method status="PASS" signature="updatePerson()[pri:0, instance:tests.Persontest@e45f292]" name="updatePerson" duration-ms="10" started-at="2017-09-13T19:15:57Z" depends-on-methods="tests.Persontest.getPersonById, tests.Persontest.addPerson" finished-at="2017-09-13T19:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updatePerson -->
        <test-method status="PASS" signature="deletePerson()[pri:0, instance:tests.Persontest@e45f292]" name="deletePerson" duration-ms="10" started-at="2017-09-13T19:15:57Z" depends-on-methods="tests.Persontest.getPersonById, tests.Persontest.addPerson, tests.Persontest.updatePerson" finished-at="2017-09-13T19:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deletePerson -->
        <test-method status="FAIL" signature="getAllPersons()[pri:0, instance:tests.Persontest@e45f292]" name="getAllPersons" duration-ms="43" started-at="2017-09-13T19:15:57Z" depends-on-methods="tests.Persontest.deletePerson, tests.Persontest.getPersonById, tests.Persontest.addPerson, tests.Persontest.updatePerson" finished-at="2017-09-13T19:15:57Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at tests.Persontest.getAllPersons(Persontest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getAllPersons -->
        <test-method status="FAIL" signature="getPersonsByFeatureEmpty()[pri:0, instance:tests.Persontest@e45f292]" name="getPersonsByFeatureEmpty" duration-ms="8" started-at="2017-09-13T19:15:57Z" depends-on-methods="tests.Persontest.deletePerson, tests.Persontest.getPersonById, tests.Persontest.addPerson, tests.Persontest.updatePerson" finished-at="2017-09-13T19:15:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [12] but found [13]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [12] but found [13]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at org.testng.Assert.assertEquals(Assert.java:398)
	at tests.Persontest.getPersonsByFeatureEmpty(Persontest.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPersonsByFeatureEmpty -->
        <test-method status="PASS" signature="getPersonsByFeatureFull()[pri:0, instance:tests.Persontest@e45f292]" name="getPersonsByFeatureFull" duration-ms="10" started-at="2017-09-13T19:15:57Z" depends-on-methods="tests.Persontest.deletePerson, tests.Persontest.getPersonById, tests.Persontest.addPerson, tests.Persontest.updatePerson" finished-at="2017-09-13T19:15:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getPersonsByFeatureFull -->
      </class> <!-- tests.Persontest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
